### ISSUE TITLE
Использовать хэш от юзер айди в статах

### ISSUE THREAD

**Issue by bxkr** [OctoDiary/OctoDiary-kt#21]
Сейчас используется случайный uuid, но это сложно трекать, поэтому в stats/enter лучше класть хэш от юзер айди. Это будет анонимно и при переустановке приложения будет продолжаться запись в значение этого ключа

**Comment by pixwet** [comment]
Сделано в коммите [a54d0ac](https://github.com/OctoDiary/OctoDiary-kt/commit/a54d0ac14fbe3f10d075b5e8c1aed761d1ed4803).
