### ISSUE TITLE
Сделать более подробным раздел оценок по предмету

### ISSUE THREAD

**Issue by pixwet** [OctoDiary/OctoDiary-kt#24]
Сейчас рейтинг грузится краткий, т.е. только текущий учебный период и последние 5 оценок, необходимо изменить метод получения оценок и адаптировать под все периоды и оценки

**Comment by bxkr** [comment]
Действительно, надо использовать другой эндпоинт для получения полной информации об оценках по предметам =>
Перейти с `family/mobile/v1/subject_marks/short` на `family/mobile/v1/subject_marks`

Думаю тоже сделать к 2.1.0

**Comment by bxkr** [comment]
Сделано в ветке 24-marks-ext
