### ISSUE TITLE
Feature request калькулятор оценок 

### ISSUE THREAD

**Issue by mootfrost** [OctoDiary/OctoDiary-kt#33]
Очень хотелось бы видеть калькулятор среднего балла, как был в параболе: можно добавлять свои оценки кнопками с перерассчетом среднего балла 

![Screenshot_20240513-090336~2](https://github.com/OctoDiary/OctoDiary-kt/assets/75925945/be519181-8c3f-4fb8-b994-0cae070b3d7d)

**Comment by bxkr** [comment]
Сделано в a3bc0e5
