### ISSUE TITLE
приложение крашится при попытке просмотра расписания

### ISSUE THREAD

**Issue by mvnh** [OctoDiary/OctoDiary-kt#9]
не получается посмотреть расписание. приложение крашится с ошибкой java.lang.IllegalArgumentException: steps should be >= 0
at org.bxkr.octodiary.screens.navsections.daybook.DateSeekerKt$DateSeeker$1.invoke(DateSeeker.kt:98)

**Comment by bxkr** [comment]
Спасибо!
В ближайшее время переделаю раздел расписания, чтобы был нормальный календарик с датами, так как сейчас там кривая функция деления на недели, изначально думал что эта ошибка может возникать
